[workspace]
authors = ["Joonhyung Shin <joons@uchicago.edu>"]
channels = ["conda-forge"]
name = "llm-context"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.13.*"

[feature.cuda]
platforms = ["linux-64"]
system-requirements = {cuda = "12.8"}

[feature.cuda.pypi-dependencies]
torch = { version = ">=2.9.1", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.24.1", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu]
platforms = ["linux-64", "osx-arm64"]

[environments]
dsi-cuda = ["cuda"]
dsi-cpu = ["cpu"]
macos = ["cpu"]
